### PR TITLE
Add sim launch file for truck_assembly in CIC

### PR DESCRIPTION
**Pull request by mintar**
Add Gazebo launch file for the truck_assembly scenario in the CIC world.

Open TODOs:

- [ ] wait for #5 to be merged
- [ ] rebase onto noetic again
- [ ] rename `mobipick_gazebo/launch/mobipick/mobipick_cic.launch` -> `mobipick_gazebo/launch/worlds/truck_assembly_spawn_sim_objects.launch`
- [ ] delete everything except spawning the tables + objects (use `mobipick_gazebo/launch/worlds/mobipick_tables_spawn_sim_objects.launch` as a template)

### CODE REVIEW

**Comment by mintar** [comment]
@jarkenau : I've created this pull request as a place to discuss your `add-cic-sim` branch. Could you take care of the open TODOs?

**Comment by mintar** [comment]
Rebased onto noetic, cleaned up commit history a bit and force-pushed.

**Comment by oscar-lima** [comment]
See https://github.com/DFKI-NI/mobipick/commit/3b0f03cceaa9a52a0d872e46507fedeb4787f4ef , some files were already added there (to spawn objects in simulation)

**Comment by oscar-lima** [comment]
I believe this is no longer necessary, all is covered by https://github.com/DFKI-NI/mobipick/pull/5

**Pull request closed without merging**
