### PR TITLE
Multiple changes for the RIC-Bremen version of the robot

### PR DESCRIPTION
**Pull request by brean**
Modifications for the Mobipick-Robot in Bremen

### CODE REVIEW

**Comment by mintar** [comment]
Thanks for the PR! I agree with 99% of it.

The only thing we should think about are the modifications to the `mobipick.srdf.xacro`.

### First problem

When running the demo with `robot_version:=hb`, MoveIt prints lots of warnings like this:

```
[ WARN] [1690384269.437866921]: Link 'mobipick/structure_cover_back_link' is not known to URDF. Cannot disable/enable collisons. (/mobipick/move_group)
```

This concerns the following links:

* `cable_guide_terminal_element_link`
* `cable_guide_wrist_clamp_link`
* `structure_cover_back_link`
* `structure_cover_front_link`
* `structure_cover_left_link`
* `structure_cover_right_link`
* `structure_cover_top_back_link`
* `structure_cover_top_front_link`

These links don't exist on `mobipick-hb`, so we would have to add lots of more `<xacro:if value="${cable_guide_wrist_3}">` lines...

### Second problem

The SRDF file needs to be re-generated on a semi-regular basis (whenever the URDF changes). The procedure is described here:

https://github.com/DFKI-NI/mobipick#updating-the-srdf

Having lots of manual modifications, like all those `<xacro:if>` lines makes this almost impossible. It's best if the file stays as close as possible to the auto-generated version.

### Proposed solution

Let's have a two separate `mobipick.srdf.xacro` files (one for `hb` and one for `os`) and switch accordingly in the launch files. The initial `hb` one can be generated using the procedure described in the README section I linked above.

What do you think?

**Comment by mintar** [comment]
By the way, maybe we also should just add the `structure_cover` links to the `hb` variant; there's no real reason not to.

**Comment by mintar** [comment]
Ok, I've added the `structure_cover` links to the `hb` variant: #11. That should get rid of most of the warnings.

Still, the point about a separate SRDF remains valid.

**Comment by brean** [comment]
Separated files make a lot of sense :+1:

**Review by mintar — CHANGES_REQUESTED** [review]
Split `mobipick.srdf.xacro` into two files (for `os` and `hb` variant).

**Review by brean — COMMENTED** [review]
All requested changes look good

**Comment by mintar** [comment]
I'm on vacation this week, but I'll look at it next week!

**Review by mintar — APPROVED** [review]
LGTM!

**Comment by mintar** [comment]
I've rebased onto noetic, fixed some whitespace errors and squashed the "fix"-commits into their respective main commits. Tested and working, merging now!

**Pull request merged**
